### ISSUE TITLE
Paxos validity proof

### ISSUE THREAD

**Issue by prasitaGit** [nano-o/ivy-proofs#1]
I did some reading about Paxos and went through the code. Do we have to prove the validity for `round 0` only? Also what is the isolate to run for `ivy_check` and `ivy_show` in this case?

**Comment by nano-o** [comment]
Let's start by proving the validity property in isolate `abs`. Validity says that every decided value must have been proposed. Can you add that to the specification block? Then check with `ivy_check isolate=abs paxos.ivy`.

**Comment by prasitaGit** [comment]
I am trying to commit some changes to `paxos.ivy` but git is throwing this error : 
remote: Permission to nano-o/ivy-proofs.git denied to prasitaGit.

**Comment by nano-o** [comment]
Sorry, you should have access now. Please use the branch `paxos-temp`.

**Comment by prasitaGit** [comment]
It is showing that I still do not have write access. I am unable to push changes as a result of this.

**Comment by nano-o** [comment]
Are you trying to push to `master` or `paxos-temp`?

**Comment by nano-o** [comment]
Github is telling me that you have not accepted my invitation to be a collaborator. You you accept it first. Then work on `paxos-temp`.

**Comment by nano-o** [comment]
https://github.com/nano-o/ivy-proofs/invitations

**Comment by prasitaGit** [comment]
I have committed the changes. Could you let me know if this is what you wanted?

**Comment by nano-o** [comment]
Yes, that's good. Can you also add it to the `protocol` isolate?

**Comment by prasitaGit** [comment]
Done

**Comment by nano-o** [comment]
Okay, now the goal is to model the network more explicitly. As an example, I added a relation `received_vote_msg` to model receiving vote messages. Can you fix the proof?

**Comment by prasitaGit** [comment]
I have added a conjecture and `ivy_check isolate=protocol paxos.ivy` runs fine. Could you check?

**Comment by nano-o** [comment]
Okay good, looks like you get it. Now I added `network_shim_tcp.ivy`. Can you modify the `protocol` isolate in order to send and receive messages explicitly using the network shim?

**Comment by prasitaGit** [comment]
I went through the file. Do you mean to complete the TODOs in `shim` and `object msg `?

**Comment by nano-o** [comment]
Yes, but also to modify `protocol` to make use of the shim.

**Comment by nano-o** [comment]
You could start by using the shim only to send and receive vote messages, while leaving the rest as is.

**Comment by prasitaGit** [comment]
I have a couple of questions on shim. I can see that in `net.recv` both if and else if conditions are same. Do I eliminate the checks and just `call vote_handler.handle(dst,m)`? Also, specifically I have to implement the `handle` action in `module handler` right?

**Comment by nano-o** [comment]
In `net.recv`, the idea is to all the handler that corresponds to the message type.

More generally, the idea is to implement the `handle` actions in `protocol`, and to call the send action from `protocol`.

**Comment by prasitaGit** [comment]
If my understanding is right, I am able to `call protocol.cast_vote(dst,m.m_value,m.m_round)` from within `handle`. I thought of calling broadcast action (which calls send) in shim from `protocol` but am unable to do so, as I can't include ` network_shim_tcp` in paxos.

**Comment by nano-o** [comment]
Why can't you include `network_shim_tcp` in paxos.ivy?
The idea is to implement `shim.vote_handler.handle` in the `protocol` isolate, and also to call `shim.broadcast` from the `protocol` isolate in order to broadcast vote messages.

**Comment by prasitaGit** [comment]
It gives me this bunch of errors (see below). I think this is because `network_shim_tcp` also includes `paxos`.  

```
paxos.ivy(8): error: redefining node (from paxos.ivy: line 8)
paxos.ivy(70): error: redefining node (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 70)
paxos.ivy: error: redefining node.t
paxos.ivy: error: redefining node.next
paxos.ivy: error: redefining node.prev
paxos.ivy: error: redefining node.is_max
paxos.ivy(82): error: redefining node.succ (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 82)
paxos.ivy(0): error: redefining node.spec (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy(86): error: redefining node.spec.prop10 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 86)
paxos.ivy(87): error: redefining node.spec.prop11 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 87)
paxos.ivy(4): error: redefining node.spec.transitivity (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 4)
paxos.ivy(5): error: redefining node.spec.antisymmetry (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 5)
paxos.ivy(6): error: redefining node.spec.totality (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 6)
paxos.ivy: error: redefining node.spec.next[before12]
paxos.ivy: error: redefining node.spec.next[after13]
paxos.ivy: error: redefining node.spec.prev[before14]
paxos.ivy: error: redefining node.spec.prev[after15]
paxos.ivy: error: redefining node.spec.is_max[after16]
paxos.ivy(312): error: redefining node.iter (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 312)
paxos.ivy(145): error: redefining node.iter.t (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 145)
paxos.ivy(145): error: redefining node.iter.is_end (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 145)
paxos.ivy(145): error: redefining node.iter.val (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 145)
paxos.ivy(150): error: redefining node.iter.def22 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 150)
paxos.ivy(153): error: redefining node.iter.done (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 153)
paxos.ivy(154): error: redefining node.iter.ahead (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 154)
paxos.ivy(155): error: redefining node.iter.between (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 155)
paxos.ivy: error: redefining node.iter.create
paxos.ivy: error: redefining node.iter.end
paxos.ivy(0): error: redefining node.iter.spec (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy: error: redefining node.iter.spec.create[after26]
paxos.ivy: error: redefining node.iter.spec.end[after27]
paxos.ivy(0): error: redefining node.iter.impl (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy: error: redefining node.iter.impl.create[implement28]
paxos.ivy: error: redefining node.iter.impl.end[implement29]
paxos.ivy: error: redefining node.iter.iso
paxos.ivy: error: redefining node.iter.next
paxos.ivy: error: redefining node.iter.prev
paxos.ivy: error: redefining node.iter.spec.next[before36]
paxos.ivy: error: redefining node.iter.spec.next[after37]
paxos.ivy: error: redefining node.iter.spec.prev[before38]
paxos.ivy: error: redefining node.iter.spec.prev[after39]
paxos.ivy: error: redefining node.iter.impl.next[implement40]
paxos.ivy: error: redefining node.iter.impl.prev[implement41]
paxos.ivy: error: redefining node.iso_iter
paxos.ivy(315): error: redefining node.max (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 315)
paxos.ivy(318): error: redefining node.prop45 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 318)
paxos.ivy(322): error: redefining node.size (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 322)
paxos.ivy(323): error: redefining node.interp46 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 323)
paxos.ivy(324): error: redefining node.def47 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 324)
paxos.ivy(325): error: redefining node.def48 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 325)
paxos.ivy(326): error: redefining node.def49 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 326)
paxos.ivy(327): error: redefining node.def50 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 327)
paxos.ivy: error: redefining node.next[implement51]
paxos.ivy: error: redefining node.prev[implement52]
paxos.ivy: error: redefining node.is_max[implement53]
paxos.ivy: error: redefining node.iso
paxos.ivy(9): error: redefining value (from paxos.ivy: line 9)
paxos.ivy(10): error: redefining quorum (from paxos.ivy: line 10)
paxos.ivy(11): error: redefining round (from paxos.ivy: line 11)
paxos.ivy(17): error: redefining round (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 17)
paxos.ivy: error: redefining round.t
paxos.ivy: error: redefining round.next
paxos.ivy: error: redefining round.prev
paxos.ivy(26): error: redefining round.succ (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 26)
paxos.ivy(0): error: redefining round.spec (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy(30): error: redefining round.spec.prop2 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 30)
paxos.ivy(4): error: redefining round.spec.transitivity (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 4)
paxos.ivy(5): error: redefining round.spec.antisymmetry (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 5)
paxos.ivy(6): error: redefining round.spec.totality (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 6)
paxos.ivy(11): error: redefining round.spec.prop1 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 11)
paxos.ivy: error: redefining round.spec.next[after3]
paxos.ivy: error: redefining round.spec.prev[before4]
paxos.ivy: error: redefining round.spec.prev[after5]
paxos.ivy(0): error: redefining round.impl (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy(49): error: redefining round.impl.interp6 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 49)
paxos.ivy(51): error: redefining round.impl.def7 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 51)
paxos.ivy: error: redefining round.impl.next[implement8]
paxos.ivy: error: redefining round.impl.prev[implement9]
paxos.ivy: error: redefining round.iso
paxos.ivy(13): error: redefining member (from paxos.ivy: line 13)
paxos.ivy(14): error: redefining quorum_intersection (from paxos.ivy: line 14)
paxos.ivy(19): error: redefining abs (from paxos.ivy: line 19)
paxos.ivy(20): error: redefining abs.left_rnd (from paxos.ivy: line 20)
paxos.ivy(21): error: redefining abs.proposal (from paxos.ivy: line 21)
paxos.ivy(22): error: redefining abs.vote (from paxos.ivy: line 22)
paxos.ivy(23): error: redefining abs.decision (from paxos.ivy: line 23)
paxos.ivy: error: redefining abs.join_round
paxos.ivy: error: redefining abs.propose
paxos.ivy: error: redefining abs.cast_vote
paxos.ivy: error: redefining abs.decide
paxos.ivy(89): error: redefining protocol (from paxos.ivy: line 89)
paxos.ivy(91): error: redefining protocol.one_a (from paxos.ivy: line 91)
paxos.ivy(92): error: redefining protocol.one_b (from paxos.ivy: line 92)
paxos.ivy(93): error: redefining protocol.current_round (from paxos.ivy: line 93)
paxos.ivy(94): error: redefining protocol.proposal (from paxos.ivy: line 94)
paxos.ivy(95): error: redefining protocol.vote (from paxos.ivy: line 95)
paxos.ivy(96): error: redefining protocol.decision (from paxos.ivy: line 96)
paxos.ivy(99): error: redefining protocol.one_b_msg (from paxos.ivy: line 99)
paxos.ivy(102): error: redefining protocol.received_vote_msg (from paxos.ivy: line 102)
paxos.ivy: error: redefining protocol.send_1a
paxos.ivy: error: redefining protocol.send_1b
paxos.ivy: error: redefining protocol.propose
paxos.ivy: error: redefining protocol.cast_vote
paxos.ivy: error: redefining protocol.receive_vote_msg
paxos.ivy: error: redefining protocol.decide
paxos.ivy(169): error: redefining protocol.safety (from paxos.ivy: line 169)
```

**Comment by nano-o** [comment]
Yes that's the problem. Can you factor out the definitions needed by both in a separate file?

On Sat, May 23, 2020, at 12:57 PM, Prasita Mukherjee wrote:
> 

> It gives me this bunch of errors (see below). I think this is because `network_shim_tcp` also includes `paxos`.

> `paxos.ivy(8): error: redefining node (from paxos.ivy: line 8)
paxos.ivy(70): error: redefining node (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 70)
paxos.ivy: error: redefining node.t
paxos.ivy: error: redefining node.next
paxos.ivy: error: redefining node.prev
paxos.ivy: error: redefining node.is_max
paxos.ivy(82): error: redefining node.succ (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 82)
paxos.ivy(0): error: redefining node.spec (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy(86): error: redefining node.spec.prop10 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 86)
paxos.ivy(87): error: redefining node.spec.prop11 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 87)
paxos.ivy(4): error: redefining node.spec.transitivity (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 4)
paxos.ivy(5): error: redefining node.spec.antisymmetry (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 5)
paxos.ivy(6): error: redefining node.spec.totality (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 6)
paxos.ivy: error: redefining node.spec.next[before12]
paxos.ivy: error: redefining node.spec.next[after13]
paxos.ivy: error: redefining node.spec.prev[before14]
paxos.ivy: error: redefining node.spec.prev[after15]
paxos.ivy: error: redefining node.spec.is_max[after16]
paxos.ivy(312): error: redefining node.iter (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 312)
paxos.ivy(145): error: redefining node.iter.t (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 145)
paxos.ivy(145): error: redefining node.iter.is_end (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 145)
paxos.ivy(145): error: redefining node.iter.val (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 145)
paxos.ivy(150): error: redefining node.iter.def22 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 150)
paxos.ivy(153): error: redefining node.iter.done (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 153)
paxos.ivy(154): error: redefining node.iter.ahead (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 154)
paxos.ivy(155): error: redefining node.iter.between (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 155)
paxos.ivy: error: redefining node.iter.create
paxos.ivy: error: redefining node.iter.end
paxos.ivy(0): error: redefining node.iter.spec (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy: error: redefining node.iter.spec.create[after26]
paxos.ivy: error: redefining node.iter.spec.end[after27]
paxos.ivy(0): error: redefining node.iter.impl (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy: error: redefining node.iter.impl.create[implement28]
paxos.ivy: error: redefining node.iter.impl.end[implement29]
paxos.ivy: error: redefining node.iter.iso
paxos.ivy: error: redefining node.iter.next
paxos.ivy: error: redefining node.iter.prev
paxos.ivy: error: redefining node.iter.spec.next[before36]
paxos.ivy: error: redefining node.iter.spec.next[after37]
paxos.ivy: error: redefining node.iter.spec.prev[before38]
paxos.ivy: error: redefining node.iter.spec.prev[after39]
paxos.ivy: error: redefining node.iter.impl.next[implement40]
paxos.ivy: error: redefining node.iter.impl.prev[implement41]
paxos.ivy: error: redefining node.iso_iter
paxos.ivy(315): error: redefining node.max (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 315)
paxos.ivy(318): error: redefining node.prop45 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 318)
paxos.ivy(322): error: redefining node.size (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 322)
paxos.ivy(323): error: redefining node.interp46 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 323)
paxos.ivy(324): error: redefining node.def47 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 324)
paxos.ivy(325): error: redefining node.def48 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 325)
paxos.ivy(326): error: redefining node.def49 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 326)
paxos.ivy(327): error: redefining node.def50 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 327)
paxos.ivy: error: redefining node.next[implement51]
paxos.ivy: error: redefining node.prev[implement52]
paxos.ivy: error: redefining node.is_max[implement53]
paxos.ivy: error: redefining node.iso
paxos.ivy(9): error: redefining value (from paxos.ivy: line 9)
paxos.ivy(10): error: redefining quorum (from paxos.ivy: line 10)
paxos.ivy(11): error: redefining round (from paxos.ivy: line 11)
paxos.ivy(17): error: redefining round (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 17)
paxos.ivy: error: redefining round.t
paxos.ivy: error: redefining round.next
paxos.ivy: error: redefining round.prev
paxos.ivy(26): error: redefining round.succ (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 26)
paxos.ivy(0): error: redefining round.spec (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy(30): error: redefining round.spec.prop2 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 30)
paxos.ivy(4): error: redefining round.spec.transitivity (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 4)
paxos.ivy(5): error: redefining round.spec.antisymmetry (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 5)
paxos.ivy(6): error: redefining round.spec.totality (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 6)
paxos.ivy(11): error: redefining round.spec.prop1 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 11)
paxos.ivy: error: redefining round.spec.next[after3]
paxos.ivy: error: redefining round.spec.prev[before4]
paxos.ivy: error: redefining round.spec.prev[after5]
paxos.ivy(0): error: redefining round.impl (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy)
paxos.ivy(49): error: redefining round.impl.interp6 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 49)
paxos.ivy(51): error: redefining round.impl.def7 (from /home/prasita/.local/lib/python2.7/site-packages/ivy/include/1.7/order.ivy: line 51)
paxos.ivy: error: redefining round.impl.next[implement8]
paxos.ivy: error: redefining round.impl.prev[implement9]
paxos.ivy: error: redefining round.iso
paxos.ivy(13): error: redefining member (from paxos.ivy: line 13)
paxos.ivy(14): error: redefining quorum_intersection (from paxos.ivy: line 14)
paxos.ivy(19): error: redefining abs (from paxos.ivy: line 19)
paxos.ivy(20): error: redefining abs.left_rnd (from paxos.ivy: line 20)
paxos.ivy(21): error: redefining abs.proposal (from paxos.ivy: line 21)
paxos.ivy(22): error: redefining abs.vote (from paxos.ivy: line 22)
paxos.ivy(23): error: redefining abs.decision (from paxos.ivy: line 23)
paxos.ivy: error: redefining abs.join_round
paxos.ivy: error: redefining abs.propose
paxos.ivy: error: redefining abs.cast_vote
paxos.ivy: error: redefining abs.decide
paxos.ivy(89): error: redefining protocol (from paxos.ivy: line 89)
paxos.ivy(91): error: redefining protocol.one_a (from paxos.ivy: line 91)
paxos.ivy(92): error: redefining protocol.one_b (from paxos.ivy: line 92)
paxos.ivy(93): error: redefining protocol.current_round (from paxos.ivy: line 93)
paxos.ivy(94): error: redefining protocol.proposal (from paxos.ivy: line 94)
paxos.ivy(95): error: redefining protocol.vote (from paxos.ivy: line 95)
paxos.ivy(96): error: redefining protocol.decision (from paxos.ivy: line 96)
paxos.ivy(99): error: redefining protocol.one_b_msg (from paxos.ivy: line 99)
paxos.ivy(102): error: redefining protocol.received_vote_msg (from paxos.ivy: line 102)
paxos.ivy: error: redefining protocol.send_1a
paxos.ivy: error: redefining protocol.send_1b
paxos.ivy: error: redefining protocol.propose
paxos.ivy: error: redefining protocol.cast_vote
paxos.ivy: error: redefining protocol.receive_vote_msg
paxos.ivy: error: redefining protocol.decide
paxos.ivy(169): error: redefining protocol.safety (from paxos.ivy: line 169)
`

**Comment by prasitaGit** [comment]
I have been working on your previous response. Based on that I have created another file and included both `network_shim_tcp` and `paxos`. I have shifted one of the implementations (`protocol.send_1b`) in this. But doing this creates dependencies and gives errors of the form : 
```
error: External call to protocol.propose may have visible effect on protocol.proposal
combinepaxos.ivy: line 12: referenced here
```
I tried including the other implementations as well (to remove dependencies). But then it seems like I have to lift implementations of all the actions of protocol isolate to the new file.

**Comment by nano-o** [comment]
I was thinking of creating a file, let's say `sorts.ivy`, that would just contain the sort declarations needed in `network_shim_tcp.ivy`. Something like 
```
include order

instance node : iterable
type value
instance round : unbounded_sequence
```
Then you would include this file in `network_shim_tcp.ivy` and `paxos.ivy`. Now `network_shim_tcp.ivy` does not need `paxos` anymore, and you can include `network_shim_tcp` in `paxos.ivy`.

**Comment by prasitaGit** [comment]
I have added a file and done some changes (calling `broadcast` and `shim.vote_handler.handle` from `protocol` isolate in `paxos`)

**Comment by nano-o** [comment]
I created a new issue for this.
